"""DB

Revision ID: 23074c07776a
Revises: 7e34aac7a7d2
Create Date: 2024-06-08 14:08:51.059932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23074c07776a'
down_revision: Union[str, None] = '7e34aac7a7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_task_observer_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_task_executor_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_task_author_id_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_task_responsible_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'task', ['task_executor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user', 'task', ['task_author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user', 'task', ['task_observer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user', 'task', ['task_responsible_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_task_responsible_id_fkey', 'user', 'task', ['task_responsible_id'], ['id'])
    op.create_foreign_key('user_task_author_id_fkey', 'user', 'task', ['task_author_id'], ['id'])
    op.create_foreign_key('user_task_executor_id_fkey', 'user', 'task', ['task_executor_id'], ['id'])
    op.create_foreign_key('user_task_observer_id_fkey', 'user', 'task', ['task_observer_id'], ['id'])
    # ### end Alembic commands ###
